const user = [{
  "id": 1,
  "first_name": "Eleonora",
  "last_name": "Hinzer",
  "email": "ehinzer0@dedecms.com"
}, {
  "id": 2,
  "first_name": "Bianca",
  "last_name": "Himsworth",
  "email": "bhimsworth1@paginegialle.it"
}, {
  "id": 3,
  "first_name": "Gina",
  "last_name": "Rugge",
  "email": "grugge2@cbsnews.com"
}, {
  "id": 4,
  "first_name": "Renaldo",
  "last_name": "Melledy",
  "email": "rmelledy3@fastcompany.com"
}, {
  "id": 5,
  "first_name": "Cobb",
  "last_name": "Bomfield",
  "email": "cbomfield4@technorati.com"
}, {
  "id": 6,
  "first_name": "Bobbee",
  "last_name": "Brinklow",
  "email": "bbrinklow5@wix.com"
}, {
  "id": 7,
  "first_name": "Prudi",
  "last_name": "Thal",
  "email": "pthal6@i2i.jp"
}, {
  "id": 8,
  "first_name": "Wheeler",
  "last_name": "Doll",
  "email": "wdoll7@tumblr.com"
}, {
  "id": 9,
  "first_name": "Antonina",
  "last_name": "Threadgould",
  "email": "athreadgould8@gizmodo.com"
}, {
  "id": 10,
  "first_name": "Celene",
  "last_name": "Stambridge",
  "email": "cstambridge9@china.com.cn"
}]
module.exports = user
